### ISSUE TITLE
feature request: include dbt api "overrides" as optional inputs into request body

### ISSUE THREAD

**Issue by sgoley** [fal-ai/dbt-cloud-action#14]
Hello!

Was setting up the dbt-cloud-action to kick off our dbt cloud ci/cd job which builds modified artifacts. 
However, we noticed that the dbt native integration has the ability of using the `schema_override` key to set the schema for each PR. 

Was wondering if it was possible to include some of those optional keys in the "trigger job" [request](https://docs.getdbt.com/dbt-cloud/api-v2#tag/Jobs/operation/triggerRun) that this action sends.

Example would just be a string for any / all of the following: 

``` json
{
"cause": "Kicked off from Airflow",
"git_branch": "staging",
"schema_override": "dbt_cloud_pr_123",
"dbt_version_override": "0.18.0",
"target_name_override": "staging",
"timeout_seconds_override": 3000,
"generate_docs_override": true,
"threads_override": 8
}
```

I see you already send the cause so I'm assuming you'd just have to add some optional inputs for the other keys?

**Comment by skwon615** [comment]
This request is exactly what I'm looking for also - definitely excited to see this in action (pun intended)!

**Comment by sgoley** [comment]
@skwon615 I actually have this working based on my own fork of this action. Here's my current workflow description yml file:

https://gist.github.com/sgoley/af3e1f857251786afb1d739ada2e2a03

**Comment by skwon615** [comment]
This is awesome, thanks @sgoley !

**Comment by chamini2** [comment]
This is now supported, check [v4.0](https://github.com/fal-ai/dbt-cloud-action/releases/tag/v4.0) release for details.
