### ISSUE TITLE
Action reports failure when job doesn't create `run_reports.json` artifact

### ISSUE THREAD

**Issue by daniel-ferguson** [fal-ai/dbt-cloud-action#23]
We have a light CI job that essentially runs `dbt parse --warn-error` to quickly flag issues like typos in schema files. This properly succeeds/fails in dbt cloud - but since it doesn't involve doing a proper dbt run it doesn't generate any artifacts.

Currently this results in a failed github action, with the following output:

```
Run fal-ai/dbt-cloud-action@v4.1
Triggered job. https://cloud.getdbt.com...
Run: [11](...) 6739196 - Success
job finished with 'Success'
Error: There has been a problem with running your dbt cloud job:
Error: Request failed with status code 404
```

I think this is because `getArtifacts` is always called after a successful job run, and getting artifacts involves fetching `run_results.json`.

Am I using this Github Action wrong? Would it be possible to find a way to skip the need for fetching `run_results`?

**Comment by chamini2** [comment]
> Am I using this Github Action wrong? Would it be possible to find a way to skip the need for fetching run_results?

You are using it right, I think we just did not think of this case. We will try to address it soon. Or if you are interested in taking a shot at fixing it, it would be awesome!

**Comment by daniel-ferguson** [comment]
hi @chamini2 I've rustled up a PR https://github.com/fal-ai/dbt-cloud-action/pull/24. I've never worked on a Github Action before so will need a little guidance

**Comment by chamini2** [comment]
Thanks for the help @daniel-ferguson !
