### ISSUE TITLE
Node16 end of life

### ISSUE THREAD

**Issue by kingalban** [fal-ai/dbt-cloud-action#29]
Node16 is at [end of life](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), so running this action gives a warning annotation: 

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: fal-ai/dbt-cloud-action@main. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I've tested, and changing the node version in `action.yml` from `node16` to `node20` fixes it without causing any other issues. Can I submit a PR?

**Comment by chamini2** [comment]
closed in #30
