### ISSUE TITLE
Support `steps_override`

### ISSUE THREAD

**Issue by jaypeedevlin** [fal-ai/dbt-cloud-action#4]
The use case here is being able to trigger a `run-operation` with specific arguments.

If a PR would be accepted, I would be happy to take a pass at this (with the caveat that I've never contributed to a GHA before)

**Comment by turbo1912** [comment]
Yes! A PR would be gladly accepted 😄

**Comment by chamini2** [comment]
This is now supported, check [v4.0](https://github.com/fal-ai/dbt-cloud-action/releases/tag/v4.0) release for details.
