### ISSUE TITLE
Undefined issue with DBT run after it succeeds

### ISSUE THREAD

**Issue by JamesSharwin** [fal-ai/dbt-cloud-action#7]
The job appears to run perfectly with but then just randomly errors with `Error: There has been a problem with running your dbt cloud job: undefined` due to `fatal: not a git repository (or any of the parent directories): .git` (see first screenshot)

Let me know if any other details / logs / info would be useful.

Screenshots:
![Screenshot 2022-07-21 at 09 27 52](https://user-images.githubusercontent.com/46328694/180167666-6f55fdf8-7a76-4a86-a1af-513b8bef434d.png)

![Screenshot 2022-07-21 at 09 28 35](https://user-images.githubusercontent.com/46328694/180167829-11a568ff-067b-40ba-882e-28b08daf370e.png)

**Comment by chamini2** [comment]
Hello @JamesSharwin, thanks for pointing this out. This happens because right now the action expects to have the git repository checked out and entirely available

```yaml
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
```

But I am working right now on making this no longer needed.

**Comment by chamini2** [comment]
Hey, this is now fixed in https://github.com/marketplace/actions/dbt-cloud-action?version=v3.
